site_name: API Client Framework
site_description: Framework for creating class-based HTTP API consumers
repo_url: https://github.com/EnriqueSoria/api_client_framework
site_author: Enrique Soria

theme:
  name: material
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
  features:
      # - navigation.tabs
      # - navigation.tabs.sticky
      - navigation.footer
      - content.code.annotate

markdown_extensions:
  - sane_lists
  - codehilite
  - fenced_code
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.snippets

plugins:
  - social

nav:
  - Introduction: 'index.md'
  - Geting started:
      - 'getting-started/describe-endpoints.md'
      - 'getting-started/create-client.md'
  - Advanced: 'advanced/index.md'